# build
# deploy to Azure as App service using blue/green

name: Build and publish to Staging

on:
  workflow_dispatch:                                # manually triggered

jobs:
  build_unit_test:                                       
    name: build and unit test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build for Release
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test /BPCalculator/BPCalculator.csproj --collect 
  
  deploy_test_blue_green:                                             
    name: deploy to staging slot, run E2E tests, swap slots
    needs: build_unit_test
    environment:
      name: QA
      url: https://bpcalculator4u-staging.azurewebsites.net                                 
    runs-on: windows-latest
    env:
      AZURE_WEBAPP_NAME: BPCalculator4u            # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project
    steps:
    - uses: actions/checkout@v2

    # publish web app ready for deployment
    - name: Publish web app
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
    
    # Deploy to Azure app service to staging slot using publish profile for staging slot
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}                            
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}     # Define secret variable in environment
        slot-name: staging
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

   
    # blue/green
    - name: swap QA and production slots
      run: |
        az webapp deployment slot swap -n BPCalculator4u -g BPCalculator --slot staging --target-slot production 

